deps: update peft to install from pypi
caikit/caikit-nlp pull request #265
Opened 2023-11-07 18:33 UTC by anhuong

relates to: #263

2023-11-07 18:36 UTC, anhuong commented
I tested this by running the tox unit tests and by running the `Getting_Started` jupyter notebook. I haven't worked with NLP too much, is there another way that this should be tested? Also, it looks like that on the next release tag it will trigger the pypi push - does this need to be tested?

2023-11-07 20:05 UTC, gkumbhat commented
@anhuong thanks for fixing the package here @anhuong . We would need to do an end to end training test with this, to make sure the training goes through smoothly for seq2seq and causal-lm models and also we are able to do inferencing on the tuned prompts. 🤔

2023-11-08 15:13 UTC, gabe-l-hart commented on pyproject.toml
> +    "peft>=0.6.0",
I think it's safer to guard against breaking changes. More annoying to maintain, but safer

```suggestion
    "peft>=0.6.0,<0.7.0",
```

2023-11-13 19:05 UTC, gkumbhat approved these changes
LGTM

2023-11-13 19:06 UTC, gkumbhat commented
@anhuong actually lets go with @dtrifiro 's idea of pinning PEFT. That would be a more resilient way of handling for this case.

2023-11-13 19:06 UTC, gkumbhat requested changes
Lets go with @dtrifiro's suggestion of pinning peft, that would be a bit more resilient to sudden or surprise breakage

2023-12-12 22:17 UTC, evaline-ju commented
Verified training ability and inference after deployment  (PT, MPT on causal lm [bloom] and seq2seq [flan-t5-xl])

Due to small training differences with the HF trainer (on the latest changes `0.4.0`/current main) I verified that results were consistent on inference for the same models

With only a peft change (I.e. no rebase/latest caikit-nlp updates, off `0.3.3` changes) I was able to confirm same results from two prompt tuned causal-lm (bloom) models

2023-12-12 22:20 UTC, evaline-ju approved these changes
LGTM

2023-12-13 05:20 UTC, merged