added tokenization tasks to serve tokenization requests
caikit/caikit-nlp pull request #325
Opened 2024-02-21 22:30 UTC by swith004

Added tokenization tasks in order to serve tokenization request and return the token count

2024-02-21 23:03 UTC, evaline-ju requested changes
Thanks for the contribution! A couple asks:
- A few small unit tests would be helpful for the new module function. We should strive for tests on any new functionality. A section like for the streaming tests https://github.com/caikit/caikit-nlp/blob/main/tests/modules/text_generation/test_text_generation_tgis.py#L135-L161 on each module might be useful to reference.
- We will likely want to allow for the tokenization to also run on prompt tuned models so it'd be good to have the same update here: https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/modules/text_generation/peft_tgis_remote.py
- [After all updates] For releasing we will want this duplicated to the `release-0.3` branch in order to also release this functionality without embeddings.

2024-02-23 18:25 UTC, swith004 commented on caikit_nlp/modules/text_generation/text_generation_tgis.py
> +    @TokenizationTask.taskmethod()
@evaline-ju  - can you explain about this being a "multi-task"? It seems the other task in the file are TextGenerationTask, so not clear on the changes requested here for the TokenizationTask...

2024-02-23 18:31 UTC, evaline-ju commented on caikit_nlp/modules/text_generation/text_generation_tgis.py
> +    @TokenizationTask.taskmethod()
before with only `TextGenerationTask` this was only single-task not multitask. By adding the TokenizationTask this becomes a multitask module like the link. We should make sure the module accounts for this by listing the tasks in the decorator

2024-02-23 18:58 UTC, swith004 commented on caikit_nlp/modules/text_generation/text_generation_tgis.py
> +    @TokenizationTask.taskmethod()
Oh, I understand what you mean now. Thanks @evaline-ju

2024-02-26 21:56 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +            token_count=response.token_count,
we were not meaning to include the tokens here. thanks - good catch!

2024-02-26 21:57 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +                tokens and input token count
done!

2024-02-26 21:57 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +            "<NLP72700256E>",
done!

2024-02-26 21:58 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +        # In case internal client is not configured - generation
modified this comment!

2024-02-26 21:58 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +            {}
done!

2024-02-26 21:58 UTC, swith004 commented on caikit_nlp/modules/text_generation/text_generation_tgis.py
> +           text to tokenize
thanks - done!

2024-02-26 21:59 UTC, swith004 commented on caikit_nlp/toolkit/text_generation/tgis_utils.py
> +            "Backend must be configured and loaded for generate",
thanks - edited message

2024-02-27 16:49 UTC, swith004 commented on caikit_nlp/modules/text_generation/peft_tgis_remote.py
> +        text: str
done!

2024-02-27 17:05 UTC, swith004 commented
> one tiny nit but otherwise lgtm! You'll need a duplicate PR to `release-0.3` as well for now

@tharapalanivel should I make the duplicate PR for the `release-0.3` before or after these changes get merged?

2024-02-27 21:15 UTC, swith004 commented
> Thanks for the contribution! A couple asks:
> 
>     * A few small unit tests would be helpful for the new module function. We should strive for tests on any new functionality. A section like for the streaming tests https://github.com/caikit/caikit-nlp/blob/main/tests/modules/text_generation/test_text_generation_tgis.py#L135-L161 on each module might be useful to reference.
> 
>     * We will likely want to allow for the tokenization to also run on prompt tuned models so it'd be good to have the same update here: https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/modules/text_generation/peft_tgis_remote.py
> 
>     * [After all updates] For releasing we will want this duplicated to the `release-0.3` branch in order to also release this functionality without embeddings.

@evaline-ju - merging is still block despite Thara's approval and the changes you requested. Not sure how to proceed

2024-02-27 21:17 UTC, evaline-ju approved these changes

2024-02-27 21:17 UTC, merged